# Generated by Django 6.0 on 2025-12-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('minutes', models.IntegerField(default=0)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('tags', models.TextField(blank=True)),
                ('nutrition', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
